
-- MySQL Script generated by MySQL Workbench
-- Mon Jan 19 18:40:14 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema AdvanceIT_skill_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AdvanceIT_skill_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AdvanceIT_skill_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `AdvanceIT_skill_test` ;

-- -----------------------------------------------------
-- Table `AdvanceIT_skill_test`.`Market`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdvanceIT_skill_test`.`Market` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `AdvanceIT_skill_test`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdvanceIT_skill_test`.`Company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `marketId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `marketId_idx` (`marketId` ASC),
  CONSTRAINT `market_key`
    FOREIGN KEY (`marketId`)
    REFERENCES `AdvanceIT_skill_test`.`Market` (`id`));


-- -----------------------------------------------------
-- Table `AdvanceIT_skill_test`.`ContactDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdvanceIT_skill_test`.`ContactDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NULL,
  `lastName` VARCHAR(255) NULL,
  `phoneNumber` VARCHAR(255) NULL,
  `isDuplicate` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `AdvanceIT_skill_test`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdvanceIT_skill_test`.`Contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companyId` INT NOT NULL,
  `contactDetailId` INT NOT NULL,
  `createDate` DATE NOT NULL ,
  `lastContactDate` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `companie_key_idx` (`companyId` ASC),
  INDEX `clients_key_idx` (`contactDetailId` ASC),
  CONSTRAINT `companies_key`
    FOREIGN KEY (`companyId`)
    REFERENCES `AdvanceIT_skill_test`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `clients_key`
    FOREIGN KEY (`contactDetailId`)
    REFERENCES `AdvanceIT_skill_test`.`ContactDetails` (`id`));

